//It's really quite simple. You take a person's most marked physical feature, compare it to genitalia (male, female or animal), and end with the suffix -bag, -wipe or -muncher. You can also add an optional reference to excretion from any of the glorious openings offered by the human body. - http://www.betterofftedinsults.com/

//fill input box of id 'id' with insult generated by genInsult()
function fillBox(id)
{
	document.getElementById(id).value=genInsult();
}

//generate an insult 
//Ex from show: "Your head looks like a lizard butt flap you snot wipe."
//Ex from show: "Your eyes look like two beady rabbit pellets on the face of a monkey-licking puss ball."
function genInsult(){
	//get the selected body part 'bp'
	var bplist=document.getElementById("bplist");
	var bp = bplist.options[bplist.selectedIndex].text;
	//if the user selects the blank option, clear the box
	if(bp==""){
		return "";
	}
	
	//A list of pairs of genitalia and plurality (0-not plural, 1-plural)
	var genListNum = [
		["Bartholin's glands",1],
		["cervix",0],
		["clitoris",0],
		["clitoral frenulum",0],
		["clitoral glans",0],
		["glans clitoridis",0],
		["clitoral hood",0],
		["fallopian tubes",1],
		["labium",0],
		["labia majora",0],
		["labia minora",0],
		["frenulum of labia minora",0],
		["ovaries",1],
		["Skene's gland",0],
		["uterus",0],
		["vagina",0],
		["vulva",0],
		["bulbourethral glands",1],
		["epididymis",0],
		["penis",0],
		["foreskin",0],
		["frenulum of penis",0],
		["glans penis",0],
		["prostate",0],
		["scrotum",0],
		["seminal vesicles",1],
		["testicles",1],
		["butt flap",0],
	];

	var suffixList = ["bag","wipe","muncher","tard","wad"];
	var excrList = ["dirt", "doo-doo", "dung", "puss", "excreta", "feces", "ordure", "poop", "scat", "waste", "snot"];
	var mwaList = ["man", "lady", "lizard","rabbit","mouse","monkey"];

	//select random man, woman, or animal
	var mwa = mwaList[Math.floor((Math.random()*mwaList.length))];
	//select [genitalia,pl] pair, pull out genitalia and form of verb that matches in number
	var genPair = genListNum[Math.floor((Math.random()*genListNum.length))];
	var gen = genPair[0];//alert(gen)
	//var verb = "look"+function suffix(p){if(p){return "";}else{return "s";}}(genPair[1]);
	//select random excretion
	var excr = excrList[Math.floor((Math.random()*excrList.length))];
	//select random suffix
	var suffix = suffixList[Math.floor((Math.random()*suffixList.length))];
	
	return "Your "+bp+" looks like a "+mwa+"'s "+excr+" "+suffix+".";
}




